config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "boats#index"

  resources :boats, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end

  # resources :bookings, only: [:index]


  resources :bookings do
    resources :reviews, only: [:new, :create, :index]
  end

  get 'dashboard', to: 'pages#dashboard'
  resources :users, only: [:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  validates :price_per_day, numericality: { greater_than: 1, message: "must be more than 0" }
  validates :year_production, numericality: { less_than_or_equal_to: 2024, message: "must be 2024 or earlier" }

  def self.available(start_date, end_date, boat_name = nil)
    query = left_joins(:bookings)
      .where('bookings.id IS NULL OR (bookings.start_date > ? OR bookings.end_date < ?)', end_date, start_date)
      .distinct
    query = query.where("name ILIKE ?", "%#{boat_name}%") if boat_name.present?

    query
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :boat
  belongs_to :user
  has_one :review
  has_paper_trail save_changes: true

  after_save :calculate_amount

  validates :end_date, presence: { message: "End date can't be blank" }
  validates :start_date, presence: { message: "Start date can't be blank" }
  validate :end_date_after_start_date
  validate :no_overlapping_bookings

  private

  def calculate_amount
    return unless saved_change_to_end_date? && saved_change_to_start_date?

    total_amount = (end_date - start_date).to_i * boat.price_per_day
    self.update(total_amount: total_amount)
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "must be after start date") if end_date <= start_date
  end

  def no_overlapping_bookings
    return if start_date.blank? || end_date.blank?

    overlapping_bookings = Booking.where(boat_id: boat_id)
                                  .where.not(id: id)
                                  .where("(start_date, end_date) OVERLAPS (?, ?)", start_date, end_date)

    if overlapping_bookings.exists?
      errors.add(:end_date, " is already booked for the selected boat")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many :boats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @boats = Boat.all

    if params[:search].present?
      if params[:search][:start_date].present? && params[:search][:end_date].present?
        start_date = Date.parse(params[:search][:start_date])
        end_date = Date.parse(params[:search][:end_date])
        boat_name = params[:search][:boat_name]
        @boats = @boats.available(start_date, end_date, boat_name)
      elsif params[:search][:boat_name].present?
        boat_name = params[:search][:boat_name]
        @boats = @boats.where("name ILIKE ?", "%#{boat_name}%")
      end

      sort_boats(params[:search])
      @boats = [] if @boats.empty?
    end
  end

  def new
    @boat = Boat.new
  end

  def show
    @boat = Boat.find(params[:id])
    @bookings = @boat.bookings
    @reviews = Review.where(booking: @bookings)
  end

  def create
    @boat = Boat.new(boat_params)
    if @boat.save
      redirect_to boat_path(@boat)
    else
      render :new, status: :unprocessable_entity

      # render :new, status: :unprocessable_entity
    end
  end

  private

  def sort_boats(search_params)
    case search_params[:sort_price]
    when 'price_asc'
      @boats = @boats.order(price_per_day: :asc)
    when 'price_desc'
      @boats = @boats.order(price_per_day: :desc)
    end
    if ['rating_asc', 'rating_desc'].include?(search_params[:sort_rating])
      @boats = @boats.sort { |boat_1, boat_2|
        avg_1 = Review.where(booking: boat_1.bookings).average(:rating) || 0
        avg_2 = Review.where(booking: boat_2.bookings).average(:rating) || 0

        avg_1 - avg_2
      }
      @boats.reverse! if search_params[:sort_rating] == 'rating_desc'
    end

  end

  def boat_params
    params.require(:boat).permit(:name, :description, :price_per_day, :year_production, :user_id, photos: [])
  end

  def search_params
    params.require(:search).permit(:boat_name, :start_date, :end_date, :sort_price, :sort_rating)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_boat, only: %i[new create edit update]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authenticate_user!

  # def index
  #   @bookings = current_user.bookings.includes(:boat)
  # end

  def edit
    @booking = current_user.bookings.find(params[:id])
  end

  def update
    @booking = current_user.bookings.find(params[:id])

    if @booking.update(booking_params)
      flash[:notice] = "Your booking was successfully updated."
      redirect_to edit_booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @boat_to_book = @boat
    @booking = Booking.new
  end

  def create
    @boat_to_book = @boat
    @booking = Booking.new(booking_params)
    @booking.boat = @boat
    @booking.user_id = current_user.id
    if @booking.save
      flash[:notice] = "Your booking was created successfully !"
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_boat
    if params[:action] == 'new' || params[:action] == 'create'
      @boat = Boat.find(params[:boat_id])
    elsif params[:action] == 'edit' || params[:action] == 'update'
      booking = Booking.find(params[:id])
      @boat = booking.boat
    end
  end


  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_amount, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def dashboard
    flash.keep
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @booking = Booking.find(params[:booking_id])
    @review = @booking.build_review
  end


  def create
    @booking = Booking.find(params[:booking_id])
    @review = @booking.build_review(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to boats_path(@booking.boat_id), notice: 'Review was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
 end

 def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to dashboard_path, notice: "Profile updated"
    else
      render :new, status: :unprocessable_entity
      redirect_to dashboard_path
    end
 end
  private

   def user_params
    params.require(:user).permit(:email)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/index.html.erb
  <!-- Video Background Section -->
  <div class="video-back-home-page">
    <video autoplay muted loop class="video-bck">
      <source src="<%= video_path("background.mp4") %>" type="video/mp4">
    </video>
    <div class="row justify-content-center float-start" style="margin-right: 0px">
    <div class="col-sm-8 my-3 bg-light rounded mt-5 mb-5">
      <h1 class="mb-4 mt-1" style="font-family: Garamond;">The best solution for your yacht rental</h1>
      <p style="font-family: Garamond;">Private yacht rentals and bareboat charters for your next boating trip.</p>
      <%= simple_form_for :search, url: boats_path, method: :get, html: { class: "" } do |f| %>
        <div class="row">
          <div class="form-field col-lg-6 mt-5 mb-3">
            <label>Search for a boat</label>
            <%= f.input :boat_name, placeholder: "", label: false, input_html: { class: "form-control" }, wrapper: false %>
          </div>
          <div class="form-field col-lg-6 mt-5 mb-3">
            <label>Sort by Price</label>
            <%= f.input :sort_price, collection: [['Cheapest to Most Expensive', 'price_asc'], ['Most Expensive to Cheapest', 'price_desc']], prompt: "Select Order", label: false, input_html: { class: "form-control" }, wrapper: false %>
          </div>
          <div class="form-field col-lg-6 mb-3">
            <label>Pick starting date</label>
            <input id="start_date" type="text" class="form-control" placeholder="DD/MM/YYYY" data-controller="datepicker" data-datepicker-target="start" name="search[start_date]">
          </div>
          <div class="form-field col-lg-6 mb-3">
            <label>Pick returning date</label>
            <input id="end_date" type="text" class="form-control" placeholder="DD/MM/YYYY" data-controller="datepicker" data-datepicker-target="end" name="search[end_date]">
          </div>
          <div class="form-field col-lg-6 mb-3">
            <label>Sort by Rating</label>
            <%= f.input :sort_rating, collection: [['Best to Worst Rated', 'rating_desc'], ['Worst to Best Rated', 'rating_asc']], prompt: "Select Order", label: false, input_html: { class: "form-control" }, wrapper: false %>
          </div>
          <div class="form-field col-lg-12 mb-2 mx-auto">
            <%= f.submit "Search", class: "btn search-btn submit-btn", id: "form-btn" %>
          </div>
        </div>
      <% end %>
    </div>
   </div>
  </div>

<div class="container mt-5">
  <!-- Boat Cards Section -->
  <% if @boats.any? %>
        <div class="cards-home-page mt-5">
        <div class="row mt-5">
          <% @boats.each do |boat| %>
            <%= link_to boat_path(boat), class: "col-md-4 mb-4 mt-5 text-decoration-none" do %>
              <div class="card boat-card h-100 d-flex flex-column">
                <div class="boat-card-image rounded-top">
                  <div id="<%= "boatCarousel-#{boat.id}" %>" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                      <% if boat.photos.attached? %>
                        <% boat.photos.each_with_index do |photo, index| %>
                          <div class="carousel-item <%= 'active' if index.zero? %>">
                            <%= cl_image_tag(photo.key, height: 300, width: 550, crop: :fill, class: 'd-block w-100 boat-img') %>
                          </div>
                        <% end %>
                      <% else %>
                        <div class="carousel-item active">
                          <div class="boat-img" style="background-image: url('https://source.unsplash.com/random/?boat'); height: 300px; background-size: cover;"></div>
                        </div>
                      <% end %>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="<%= "#boatCarousel-#{boat.id}" %>" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="<%= "#boatCarousel-#{boat.id}" %>" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
                </div>
                <div class="card-body d-flex flex-column flex-grow-1 position-relative">
                  <h5 class="card-title text-dark"><%= boat.year_production %> <%= boat.name %></h5>
                  <p class="card-text flex-grow-1 text-dark"><%= boat.description %></p>
                  <div class="mt-auto d-flex justify-content-between align-items-center">
                    <span class="text-dark"><strong><%= boat.price_per_day %></strong> CHF / day</span>
                    <div class="review-stars">
                      <i class="fas fa-star text-warning"></i> <%= (Review.where(booking: boat.bookings).average(:rating)).to_i %>/5
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="boat-show-card text-center">
        <h6 class='ps-3'> No results found </h6>
      </div>
  <% end %>
</div>

app/views/boats/new.html.erb
<div class="container py-5" id="boat-margin">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new boat</h3>
        <%= simple_form_for @boat do |f| %>
          <%= f.input :name, placeholder: 'Enter your boat name' %>
          <%= f.input :description, placeholder: 'Write a description' %>
          <%= f.input :price_per_day%>
          <%= f.input :year_production %>
          <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %> <!--Value will be changed with current_user.id-->
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
      <%= render "shared/flashes" %>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<div class="container margin-top-negative">
  <!--title-->
  <div class="row">
    <h3 id="show-boat-name"><%=@boat.name %></h3>
    <div class='d-flex'>

      <p> ⭐<%= (@reviews.average("rating")).to_i %>/5 (<%= @reviews.count %>) reviews</p>
    </div>
  </div>
  <!--images-->
  <div class="grid-container">
      <% if @boat.photos.attached? %>
        <div class="grid-item big" style="width: 100%; height: 100%;">
          <%= cl_image_tag(@boat.photos[0].key, height: '500', width: '550',crop: :fill, class: 'd-block h-100 w-100 boat-img') %>
        </div>
        <% @boat.photos.drop(1).each do |photo| %>
            <div class="grid-item">
              <%= cl_image_tag(photo.key, height: 300, width: 550, crop: :fill, class: 'd-block w-100 boat-img') %>
            </div>
        <% end %>
      <% else %>
        <div class="grid-item big" style="width: 100%; height: 100%;">
          <div class="boat-img" style="background-image: url('https://source.unsplash.com/random/?boat')"></div>
        </div>
        <% 4.times do %>
          <div class="grid-item">
            <div class="boat-img" style="background-image: url('https://source.unsplash.com/random/?boat')"></div>
          </div>
        <% end %>
      <% end %>
  </div>

  <div class="row">
    <div class="col-8 ">
      <!-- this boat owned by-->
      <div class="boat-show-card" id ='owned-by'>
          <h6 class='ps-3'> This boat owned by <%= @boat.user.first_name %> </h6>

        <p class="boat-show-description ps-3"><%= a = rand(3..10)%> people · <%=rand(1..5)%> cabins · <%=a%> berths · <%=rand(1..2)%> bathrooms</p>
        <p class="card-text ps-3">Year production: <strong><%= @boat.year_production %></strong></p>

      </div>
      <!--Description of owner -->
      <div class="boat-show-card">
        <h4 class='ps-3'> Description of <%= @boat.user.first_name %>'s boat.</h4>
        <p class="boat-show-description ps-3"> <%= @boat.description %></p>
        <p class="boat-show-description ps-3"> <%= raw @boat.details %></p>
      </div>
      <div class="boat-show-card">
        <h4><i class="bi bi-anchor"></i> Equipments of the sailboat</h4>
        <div class="row">
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fas fa-anchor"></i> Dinghy</li>
              <li class="list-group-item"><i class="fas fa-ship"></i> Dinghy's motor</li>
              <li class="list-group-item"><i class="fas fa-swimmer"></i> Paddle board</li>
              <li class="list-group-item"><i class="fas fa-wrench"></i> Electric winches</li>
              <li class="list-group-item"><i class="fas fa-flag"></i> Gennaker</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fas fa-compass"></i> Autopilot</li>
              <li class="list-group-item"><i class="fas fa-umbrella-beach"></i> Bimini</li>
              <li class="list-group-item"><i class="fas fa-anchor"></i> Bow thruster</li>
              <li class="list-group-item"><i class="fas fa-swimmer"></i> Kayak</li>
              <li class="list-group-item"><i class="fas fa-ship"></i> Snorkelling equipment</li>
            </ul>
          </div>
        </div>
      </div>



      <div class="boat-show-card">
        <h3>Reviews</h3>
        <% if  @reviews.any? %>
          <div class="flex">
            <% @reviews.each do |review| %>
              <div class="flex ms-3">
                <p>⭐<%= (review.rating).to_i %>/5 <%= review.user.first_name %> <small>  (<%= review.created_at.strftime("%d.%m.%Y") %>)</small>:</p>
                <p><strong><%= review.comment %></strong> </p>
                <br>
              </div>
            <% end %>
          </div>
          <% else %>
          <div class="flex ms-3">
            <p> No reviews yet...</p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-4 mt-3">
      <div class="card shadow border-none" id="sticky">
        <div class="card-body">
          <h3 class="card-title">Details</h3>
          <div class="">
            <div class="me-3 text-align-center">
              <p class="card-text"><strong><%= @boat.price_per_day %></strong> CHF / day</p>
            </div>
          </div>

          <% if @boat.bookings.present? %>
          <div class="alert alert-danger mt-5 ms-3" role="alert">
            <p class="mb-0">Not available:</p>

            <% @bookings.each do |booking|%>
            <p class="mb-0">from: <strong><%=booking.start_date%></strong> to: <strong><%=booking.end_date%></strong></p>
            <%end%>
          </div>
          <% else %>
          <div class="alert alert-success mt-5 ms-3" role="alert">
            <p class="mb-0">Available: NOW 🚢</p>
          </div>
          <% end %>

          <div class="d-flex justify-content-center mt-3">
            <%= link_to "Book this boat!", new_boat_booking_path(@boat), class: "btn", style: "background-color: rgb(88,201,250);" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container my-5">
  <div class="row">
    <!-- Colonne du formulaire de modification -->
    <div class="col-md-6">
      <div class="form-home text-center mb-5">
        <h3>Update Booking</h3>
        <p class="lead">Please fill in the details to update your booking.</p>
      </div>

      <%= form_for @booking, html: { class: 'needs-validation', novalidate: "" } do |f| %>
        <div class="mb-3">
          <%= f.label :start_date, class: 'form-label' %>
          <%= f.date_field :start_date, class: 'form-control', required: true %>
        </div>

        <div class="mb-3">
          <%= f.label :end_date, class: 'form-label' %>
          <%= f.date_field :end_date, class: 'form-control', required: true %>
        </div>

        <div class="mb-3">
          <%= f.label :comment, 'Comment (optional)', class: 'form-label' %>
          <%= f.text_area :comment, rows: 3, class: 'form-control' %>
        </div>

        <div class="actions text-center">
          <%= f.submit 'Update my booking', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>



    <div class="container my-5">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              Summary of Booking Changes
            </div>
            <div class="card-body">
              <div class="row">
                <!-- Modification Date -->
                <div class="col-md-3">
                  <h5 class="card-title">Modification Date</h5>
                  <% @booking.versions.each do |version| %>
                    <div class="mb-4"> <!-- Ajout d'une marge en bas pour chaque élément -->
                      <p class="card-text">
                        <%= version.created_at.strftime("%d/%m/%Y %H:%M") %>
                      </p>
                    </div>
                  <% end %>
                </div>

                <!-- Start Date Changes -->
                <div class="col-md-3">
                  <h5 class="card-title">Start Date Changes</h5>
                  <% @booking.versions.reverse.each do |version| %>
                    <% booking_version = version.reify %>
                    <% next unless booking_version %>
                    <div class="mb-2"> <!-- Ajout d'une marge en bas pour chaque élément -->
                      <p class="card-text">
                        <strong>From: </strong><%= booking_version.start_date %> <br>
                        <strong>To: </strong><%= version.next&.reify&.start_date || @booking.start_date %>
                      </p>
                    </div>
                  <% end %>
                </div>

                <!-- End Date Changes -->
                <div class="col-md-3">
                  <h5 class="card-title">End Date Changes</h5>
                  <% @booking.versions.reverse.each do |version| %>
                    <% booking_version = version.reify %>
                    <% next unless booking_version %>
                    <div class="mb-2"> <!-- Ajout d'une marge en bas pour chaque élément -->
                      <p class="card-text">
                        <strong>From: </strong><%= booking_version.end_date %> <br>
                        <strong>To: </strong><%= version.next&.reify&.end_date || @booking.end_date %>
                      </p>
                    </div>
                  <% end %>
                </div>

                <!-- Total Amount Changes -->
                <div class="col-md-3">
                  <h5 class="card-title">Total Amount Changes</h5>
                  <% @booking.versions.reverse.each do |version| %>
                    <% booking_version = version.reify %>
                    <% next unless booking_version %>
                    <div class="mb-2"> <!-- Ajout d'une marge en bas pour chaque élément -->
                      <p class="card-text">
                        <strong>From: </strong><%= booking_version.total_amount %><br>
                        <strong>To: </strong><%= version.next&.reify&.total_amount || @booking.total_amount %>
                      </p>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container rounded bg-white mt-5 mb-5" >
  <div class="row">

    <!-- User Profile (on the left) -->
    <div class="col-md-3 border-right" id="dashboard-margin">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg">
        <span class="font-weight-bold"> <%= current_user.first_name %> <%= current_user.last_name %> </span>
        <span class="text-black-50"><%= current_user.email %></span>
      </div>
    </div>

    <!-- Profile Settings (on the right) -->
    <div class="col-md-5">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="text-right">Profile Settings</h4>
        </div>

        <%= simple_form_for current_user, html: { class: 'mt-2' } do |f| %>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :last_name, label: "Last name",  disabled: true %>
            </div>
            <div class="col-md-6">
              <%= f.input :first_name, label: "First name", disabled: true %>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-12">
              <%= f.input :email, label: "Email" %>
            </div>
            <div class="col-md-12">
              <%= f.input :created_at, label: "Account created date", disabled: true, as: :string,
               input_html: { data: { controller: "datepicker"} } %>
            </div>
          </div>

          <div class="mt-5 text-center">
            <%= f.submit "Edit profile", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="booking-h3-style">
    <h3>My bookings</h3>
  </div>
  <div class="row" id="profile-cards">
  <% current_user.bookings.each do |booking| %>
    <div class="col-md-4">
      <div class="card" style="width: 18rem; background-image: url('https://source.unsplash.com/random/?boat'); background-size: cover; color: white; overflow: hidden; margin-bottom: 20px">
        <div class="card-body" style="background-color: rgba(0,0,0,0.5);">
          <h5 class="card-title"><strong><%= booking.boat.name %></strong></h5>
          <p class="card-text">
            Rental dates: <%= booking.start_date %> to <%= booking.end_date %>
          </p>
          <p class="card-text">
            Booking cost: <%= booking.total_amount %> CHF
          </p>
          <% if booking.review.nil? %>
          <div class="btn-cards-booking">
            <% if Date.today < booking.start_date %>
              <%= link_to 'Manage my booking', edit_booking_path(booking), class: "btn btn-outline-info" %>
            <% end %>
            <% if Date.today > booking.end_date %>
              <%= link_to 'Add a review', new_booking_review_path(booking_id: booking.id), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <% else %>
            <p>Review already sent <i class="fa-solid fa-check"></i></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_header.html.erb
 <%= render "shared/flashes" %>
  <div class="navbar navbar-expand-sm navbar-light bg-white shadow-sm sticky-top">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to boats_path do %>
          <%= image_tag "boat-logo3.jpg", alt: "AirbnBoat Logo", class: "logo" %>
          <span class="brand-name">AirbnBoat</span>
        <% end %>
      </div>
      </div>

      <div class="float-rigt">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
              <%= link_to "Home", boats_path, class: "nav-link" %>
          </li>
          <div class="add-boat-button">
      <% if user_signed_in? %>
        <%= button_to 'Add a new Boat', new_boat_path, method: :get, class: "btn add-boat-btn" %>
      <% end %>
      </div>
          <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to current_user.first_name, dashboard_path, class: "nav-link" %>
          <% else %>
            <%= link_to "Profile", dashboard_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            <% else %>
              <%= link_to "Sign up", "/users/sign_up", class: "dropdown-item" %>
              <%= link_to "Log in", "/users/sign_in", class: "dropdown-item" %>
            <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>